### ISSUE TITLE
Excuse me, why is there such a problem?

### ISSUE THREAD

**Issue by Panhaiwei** [mister-ben/videojs-flvjs#4]
The console prints as follows：

```
E:\videojs-flvjs\scripts\build-test.js:1
(function (exports, require, module, __filename, __dirname) { import browserify from 'browserify';
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:53:10)
at Object.runInThisContext (vm.js:95:10)
at Module._compile (module.js:543:28)
at loader (E:\videojs-flvjs\node_modules\babel-register\lib\node.js:144:5)
at Object.require.extensions.(anonymous function) [as .js] (E:\videojs-flvjs\node_modules\babel-register\lib\node.js:154:7)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Function.Module.runMain (module.js:605:10)
at Object. (E:\videojs-flvjs\node_modules\babel-cli\lib_babel-node.js:154:22)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run-script" "--videojs-flvjs:ghooks_pre_push=npm run lint" "build:test"
npm ERR! node v7.9.0
npm ERR! npm v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! videojs-flvjs@0.1.2 build:test: babel-node scripts/build-test.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the videojs-flvjs@0.1.2 build:test script 'babel-node scripts/build-test.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the videojs-flvjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! babel-node scripts/build-test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs videojs-flvjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls videojs-flvjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\hywel\AppData\Roaming\npm-cache_logs\2017-10-09T09_20_08_008Z-debug.log

videojs-flvjs@0.1.2 build:js:babel E:\videojs-flvjs
babel src -d es5
ERROR: build:test: None-Zero Exit(1);
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! videojs-flvjs@0.1.2 build: npm-run-all -p build:*
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the videojs-flvjs@0.1.2 build script 'npm-run-all -p build:'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the videojs-flvjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm-run-all -p build:
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs videojs-flvjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls videojs-flvjs
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\hywel\AppData\Roaming\npm-cache_logs\2017-10-09T09_20_10_750Z-debug.log
```

**Comment by mister-ben** [comment]
I think #5 should fix this. Are you able to test that before I merge?

**Comment by Panhaiwei** [comment]
@mister-ben After testing the #5, the test passed。You can now build it properly。Thanks!

**Comment by mister-ben** [comment]
Thanks for reporting and testing
